hepsi: derle calistir
derle:
	g++ -I ./include/ -o ./lib/Nesne1.o -c ./src/Nesne1.cpp
	g++ -I ./include/ -o ./lib/Nesne2.o -c ./src/Nesne2.cpp
	g++ -I ./include/ -o ./bin/Test ./lib/Nesne1.o ./lib/Nesne2.o ./src/Test.cpp    
calistir:
	./bin/Test